name: PR Checks

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          version: __NODEVERSION__
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test:coverage
        env:
          CI: true
          NODE_ENV: ci
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          version: __NODEVERSION__
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          version: __NODEVERSION__
      - name: Install dependencies
        run: npm ci
      - name: Compile
        run: npm run compile
